### PR TITLE
Etherpad-Lite: Support docker-compose, fix JSON

### PR DESCRIPTION
**Pull request by pawohl**
- Support for docker-compose added to Etherpad-Lite with pre-configured database
- JSON creation fixed: If ETHERPAD_ADMIN_PASSWORD was not set, a trailing comma after the dbSettings was left. (1) Double quotation marks need escape. (2) settings.json is now created by node-js as ECMA-script supports JSON formatting natively.
- Customizable database port through `ETHERPAD_DB_PORT`.

### CODE REVIEW

**Comment by pawohl** [comment]
Btw, what is the benefit of removing the apt source lists with `rm -r /var/lib/apt/lists/*`?

From what I understand, the image isn't getting substantially smaller because the files will be kept in the layers below.

**Comment by pawohl** [comment]
I think a fork is better suited. Merge request has issues. Thanks for your work!

**Comment by tvelocity** [comment]
Hello,

Thanks for all your comments. I will take a look in your fork, and eventually merge back any improvements.

Cheers.

**Comment by tvelocity** [comment]
Btw, regarding /var/lib/apt/lists/*, the removal is done under the same RUN directive that populates these files. Under tis scenario, the files will not kept in any of the layers (it is one layer per Dockerfile command).

This is standard practice when writing Dockerfiles, even the official images use this (the official Wordpress image, for example https://github.com/docker-library/wordpress/blob/master/Dockerfile-debian.template )

**Pull request closed without merging**
