### PR TITLE
etherpad: updated entrypoint and README to use new docker networking features

### PR DESCRIPTION
**Pull request by vigliag**
Hi! I've updated both entrypoint.sh and README to use the new docker networking features instead of legacy links (which should still work, although I have only tried with the new method).

Addresses #17 

Thanks!

### CODE REVIEW

**Comment by tvelocity** [comment]
Thanks for your proposal! :+1: 
I will try to carve out some time in the coming days to review & test it properly, and hopefully merge it.

**Comment by y0no** [comment]
Thanks! It's really a good news for people who use docker-compose :D

**Comment by tvelocity** [comment]
So I tested this pull requests (with both linking and docker network feature), and can confirm that it works under both scenarios. Thanks for the patch!

**Comment by vigliag** [comment]
Great! :) Thank you!

**Pull request merged**
